server:
  port: 8081

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/workday-authorization-server/endpoint/jwks.json
