export enum NumbersEnum {
  WORKDAY_DEFAULT_STREET_NUMBER_FORMAT_REGEX = '^[1-9]\\d*$',
  WORKDAY_DEFAULT_POSTAL_CODE_FORMAT_REGEX = '^[0-9]{1,6}$',
  WORKDAY_DEFAULT_IBAN_FORMAT_REGEX= '^RO\\d{2}[A-Z]{4}[0-9A-Z]{16}$'

}



