spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/workday
    username: postgres
    password: 123456

