server:
  port: 8080
  #context path
  server:
    servlet:
      context-path: /workday-resource-server


spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/workday
    username: postgres
    password: 123456

  ####### resource server configuration properties
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/workday-auth-server/endpoint/jwks.json
