#server:
#  port: 8080
#  #context path
#  server:
#    servlet:
#      context-path: /workday-resource-server


spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/workday
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

app:
  jwtSecret: licentaSecretKey
  jwtExpirationMs: 86400000
